rules = [
  OrganizeImports,
  LeakingImplicitClassVal
]

# Scala 3 style: wildcard imports
OrganizeImports.groupedImports = Merge
OrganizeImports.expandRelative = false

# Ordering for OrganizeImports:
# groups run in order; "" is the "other" group.
OrganizeImports.groups = [
  "re:javax?\\."
  "scala\\."
  "*"
  "foil\\."
  "languages\\."
]
OrganizeImports.groupOverridden = false