rules = [
  OrganizeImports,
  RemoveUnused,
  LeakingImplicitClassVal
]

# Scala 3 style: wildcard imports
OrganizeImports.groupedImports = Merge
OrganizeImports.removeUnused = true
OrganizeImports.expandRelative = false

# Ordering for OrganizeImports:
# groups run in order; "" is the "other" group.
OrganizeImports.groups = [
  "re:javax?\\."
  "scala\\."
  "*"
  "foil\\."
  "languages\\."
]
OrganizeImports.groupOverridden = false

RemoveUnused.imports = true
RemoveUnused.privateToplevelParams = true
RemoveUnused.localVals = true
RemoveUnused.patternVals = true
RemoveUnused.termNames = []